"""
Typed grounding overlay — §4c. Consumer judgments about a foreign bundle,
stored beside our state, never written into the source.

Layout:
    .hologram/okf/<bundle_id>/
    ├── ingest-report.json      lint findings + counts (§7b lint section)
    ├── grounding-profile.yaml  per-concept typed-context records (I1–I3)
    ├── provenance.json         producer typing + exhaust list (I4)
    ├── temporal-index.json     anchors, staleness, temporal_reference (I2/I3)
    ├── coactivation.json       link-graph seed, broken -> not_yet_written (I5)
    └── learned-state/          runtime-owned; ingest creates, never overwrites

Keying: learned state and profile records key on concept_id (bundle-relative
path) + content_hash. A log.md append changes ONE concept's content_hash; it
must never invalidate siblings or reset learned state (§4c) — hence no
whole-bundle digest anywhere in a per-concept key.
"""

import hashlib
import json
import subprocess
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, List, Optional

from .lint import annotate
from .reader import Bundle, Concept, read_bundle
from .report import build_report

try:
    import yaml as _yaml
except ImportError:
    _yaml = None

AGENT_MARKER_RE = None  # built lazily below to keep import cheap
_AGENT_TOKENS = ('agent', 'bot', 'claude', 'gpt', 'gemini', 'llm', 'auto-generated',
                 'autogenerated', 'generated by', 'enrichment')


@dataclass
class IngestResult:
    bundle_id: str
    overlay_dir: str
    concepts: int
    report: Dict = field(default_factory=dict)


def _sha256(data: str) -> str:
    return hashlib.sha256(data.encode('utf-8')).hexdigest()


def _bundle_id(bundle: Bundle) -> str:
    index = bundle.index
    identity = index.body if index is not None else '\n'.join(sorted(bundle.concepts))
    return f'{bundle.name}-{_sha256(identity)[:12]}'


def _git_file_info(root: Path, relpath: str) -> Optional[Dict[str, str]]:
    try:
        out = subprocess.run(
            ['git', '-C', str(root), 'log', '-1', '--format=%cI|%an|%ae', '--', relpath],
            capture_output=True, text=True, timeout=10,
        )
    except (OSError, subprocess.TimeoutExpired):
        return None
    line = out.stdout.strip()
    if out.returncode != 0 or not line:
        return None
    date, _, rest = line.partition('|')
    name, _, email = rest.partition('|')
    return {'committed': date, 'author': name, 'email': email}


def _producer(concept: Concept, git_info: Optional[Dict[str, str]]) -> str:
    """I4: human | agent | unknown, only where determinable."""
    hay = ' '.join(str(concept.frontmatter.get(k, ''))
                   for k in ('producer', 'generated_by', 'author', 'source')).lower()
    if any(t in hay for t in _AGENT_TOKENS):
        return 'agent'
    body_head = concept.body[:2000].lower()
    if any(t in body_head for t in ('auto-generated', 'generated by', 'enrichment agent')):
        return 'agent'
    if git_info:
        who = (git_info['author'] + ' ' + git_info['email']).lower()
        if any(t in who for t in ('bot', 'agent', '[bot]')):
            return 'agent'
        return 'human'
    return 'unknown'


def _fs_mtime_iso(path: str) -> Optional[str]:
    try:
        ts = Path(path).stat().st_mtime
    except OSError:
        return None
    return datetime.fromtimestamp(ts, tz=timezone.utc).isoformat()


def _concept_record(concept: Concept, root: Path, now: datetime) -> Dict:
    ann = annotate(concept.body, concept.frontmatter)
    git_info = _git_file_info(root, concept.concept_id)

    as_of, source = ann['as_of'], ann['anchor_source']
    if as_of is None and git_info:
        as_of, source = git_info['committed'], 'git_mtime'
    if as_of is None:
        mtime = _fs_mtime_iso(concept.path)
        if mtime:
            as_of, source = mtime, 'fs_mtime'

    staleness_days = None
    if as_of:
        try:
            dt = datetime.fromisoformat(as_of.replace('Z', '+00:00'))
            if dt.tzinfo is None:
                dt = dt.replace(tzinfo=timezone.utc)
            staleness_days = round((now - dt).total_seconds() / 86400, 1)
        except ValueError:
            pass

    # anchored means the PRODUCER dated it (I2). Fallback anchors locate the
    # file in time for staleness but do not make a dateless concept current.
    anchored = ann['anchored']
    return {
        'concept_id': concept.concept_id,
        'content_hash': _sha256(concept.body),
        'okf_type': concept.type,
        'authority': 'informational',          # I1: hard cap for third-party
        'scope': 'bundle',
        'precedence': 'below_first_party',
        'producer': _producer(concept, git_info),
        'temporal': {
            'temporal_reference': ann['temporal_reference'],
            'anchored': anchored,
            'as_of': as_of,
            'anchor_source': source,
            'staleness_days': staleness_days,
            'servable_as_current': bool(anchored),   # dateless never current (I2)
        },
        'lint_findings': ann['findings'],
        'parse_notes': concept.parse_notes,
    }


def _log_entry_records(bundle: Bundle) -> List[Dict]:
    # I3: bare YYYY-MM-DD headings anchored on ingest; offset is unknowable
    # from the heading alone, so UTC-midnight is assumed and the assumption
    # is recorded in anchor_source. Log entries are history, not state.
    return [{
        'source': e.date and e.source,
        'heading': e.heading,
        'as_of': f'{e.date}T00:00:00+00:00',
        'anchor_source': 'log_heading_date_utc_assumed',
        'temporal_reference': 'past_completed',
    } for e in bundle.log_entries]


def _write(path: Path, payload) -> None:
    path.write_text(json.dumps(payload, indent=2, default=str) + '\n', encoding='utf-8')


def ingest_bundle(bundle_root, project_root=None, now: Optional[datetime] = None) -> IngestResult:
    """Read a bundle (read-only) and materialize/refresh its overlay."""
    bundle = read_bundle(bundle_root)
    now = now or datetime.now(timezone.utc)
    root = Path(bundle.root)
    bundle_id = _bundle_id(bundle)

    base = Path(project_root) if project_root else Path.cwd()
    overlay = base / '.hologram' / 'okf' / bundle_id
    overlay.mkdir(parents=True, exist_ok=True)
    (overlay / 'learned-state').mkdir(exist_ok=True)

    records = {cid: _concept_record(c, root, now) for cid, c in bundle.concepts.items()}

    profile = {'bundle_id': bundle_id, 'bundle_root': bundle.root,
               'ingested_at': now.isoformat(), 'concepts': records}
    if _yaml is not None:
        (overlay / 'grounding-profile.yaml').write_text(
            _yaml.safe_dump(profile, sort_keys=False, allow_unicode=True), encoding='utf-8')
    else:
        _write(overlay / 'grounding-profile.json', profile)

    _write(overlay / 'provenance.json', {
        'bundle_id': bundle_id,
        'producers': {cid: r['producer'] for cid, r in records.items()},
        # I4: agent-produced bundle content counts toward the C4 exhaust
        # numerator, not the injected-record numerator.
        'exhaust_concepts': sorted(cid for cid, r in records.items()
                                   if r['producer'] == 'agent'),
    })

    _write(overlay / 'temporal-index.json', {
        'bundle_id': bundle_id,
        'concepts': {cid: r['temporal'] for cid, r in records.items()},
        'log_entries': _log_entry_records(bundle),
    })

    _write(overlay / 'coactivation.json', {
        'bundle_id': bundle_id,
        'edges': [{'src': cid,
                   'dst': link.resolved,
                   'status': 'not_yet_written' if link.broken else 'ok'}
                  for cid, c in bundle.concepts.items() for link in c.links],
    })

    report = build_report(bundle_id, bundle, records)
    _write(overlay / 'ingest-report.json', report)

    return IngestResult(bundle_id=bundle_id, overlay_dir=str(overlay),
                        concepts=len(records), report=report)
